// <auto-generated />
using System;
using ArabaSatis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArabaSatis.Migrations
{
    [DbContext(typeof(ArabamDbContext))]
    [Migration("20250617162438_yorumlar")]
    partial class yorumlar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArabaSatis.Models.ArabaResim", b =>
                {
                    b.Property<int>("ArabaResimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArabaResimId"));

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ilanId")
                        .HasColumnType("int");

                    b.HasKey("ArabaResimId");

                    b.ToTable("ArabaResim");
                });

            modelBuilder.Entity("ArabaSatis.Models.Markalar", b =>
                {
                    b.Property<int>("MarkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarkaId"));

                    b.Property<string>("MarkaAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarkaId");

                    b.ToTable("Markalars");
                });

            modelBuilder.Entity("ArabaSatis.Models.SeriModel", b =>
                {
                    b.Property<int>("SeriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeriId"));

                    b.Property<int?>("MarkaId")
                        .HasColumnType("int");

                    b.Property<int?>("MarkalarsMarkaId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeriId");

                    b.HasIndex("MarkalarsMarkaId");

                    b.ToTable("SeriModels");
                });

            modelBuilder.Entity("ArabaSatis.Models.Yakit", b =>
                {
                    b.Property<int>("YakitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YakitId"));

                    b.Property<string>("YakitAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YakitId");

                    b.ToTable("Yakits");
                });

            modelBuilder.Entity("ArabaSatis.Models.Yorumlar", b =>
                {
                    b.Property<int>("YorumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YorumId"));

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yorum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ilanId")
                        .HasColumnType("int");

                    b.HasKey("YorumId");

                    b.ToTable("Yorumlars");
                });

            modelBuilder.Entity("ArabaSatis.Models.SeriModel", b =>
                {
                    b.HasOne("ArabaSatis.Models.Markalar", "Markalars")
                        .WithMany("SeriModels")
                        .HasForeignKey("MarkalarsMarkaId");

                    b.Navigation("Markalars");
                });

            modelBuilder.Entity("ArabaSatis.Models.Markalar", b =>
                {
                    b.Navigation("SeriModels");
                });
#pragma warning restore 612, 618
        }
    }
}
